resourceClasses:
  - uk.gov.pay.adminusers.resources.ForgottenPasswordResource
  - uk.gov.pay.adminusers.resources.HealthCheckResource
  - uk.gov.pay.adminusers.resources.InviteResource
  - uk.gov.pay.adminusers.resources.ResetPasswordResource
  - uk.gov.pay.adminusers.resources.ServiceResource
  - uk.gov.pay.adminusers.resources.UserResource
  - uk.gov.pay.adminusers.resources.ToolboxEndpointResource
readAllResources: true
sortOutput: true
prettyPrint: true

openAPI:
  info:
    description: 'Adminusers API'
    title: 'Adminusers API'
    version: 'v1.0.0'
