name: Post Merge

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

permissions:
  contents: read

concurrency: adminusers-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  consumer-contract-tests:
    needs: tests
    runs-on: ubuntu-18.04

    name: Publish and tag adminusers consumer pact
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Set up JDK 11
        uses: actions/setup-java@f69f00b5e5324696b07f6b1c92f0470a6df00780
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache pacts directory
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: target/pacts
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-pacts
      - name: Publish and tag adminusers consumer pact
        run: |
          mvn pact:publish -DPACT_BROKER_URL=https://pact-broker-test.cloudapps.digital \
          -DrunConsumerContractTests \
          -DPACT_BROKER_USERNAME=${{ secrets.pact_broker_username }} \
          -DPACT_BROKER_PASSWORD=${{ secrets.pact_broker_password }} \
          -DPACT_CONSUMER_TAG=master \
          -DPACT_CONSUMER_VERSION=${{ github.sha }}

  ledger-provider-contract-tests:
    needs: consumer-contract-tests
    uses: alphagov/pay-ledger/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: adminusers
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  connector-provider-contract-tests:
    needs: consumer-contract-tests
    uses: alphagov/pay-connector/.github/workflows/_run-pact-provider-tests.yml@master
    with:
      consumer: adminusers
      consumer_tag: master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  provider-contract-tests:
    needs: tests
    uses: alphagov/pay-ci/.github/workflows/_run-provider-contract-tests.yml@master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - provider-contract-tests
      - consumer-contract-tests
      - ledger-provider-contract-tests
      - connector-provider-contract-tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
