name: Post Merge

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency: adminusers-post-merge

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml

  provider-contract-tests:
    needs: tests
    uses: alphagov/pay-ci/.github/workflows/_run-provider-contract-tests.yml@master
    secrets:
      pact_broker_username: ${{ secrets.pact_broker_username }}
      pact_broker_password: ${{ secrets.pact_broker_password }}

  tag-release:
    needs:
      - provider-contract-tests
    permissions:
      contents: write
    uses: alphagov/pay-ci/.github/workflows/_create-alpha-release-tag.yml@master
